name: Geomatics CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: First sub-stage
        run: echo "First sub-stage"
      - name: Second sub-stage
        run: echo "Second sub-stage"

  build_publish:
    name: build_publish
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
    steps:
      - run: echo "Second Stage testing - Docker stage"
  aws_authentication:
    name: aws authentication
    runs-on: ubuntu-latest
    steps:
      - run: aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
